---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        - default.yaml
      skip: true

# redhat based
#
- block:
    - name: import EPEL GPG key
      rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1
  when:
    - ansible_os_family | lower == 'redhat'

# debian
- block:
    - name: add backports repository
      apt_repository:
        repo: deb http://ftp.de.debian.org/debian {{ ansible_distribution_release }}-backports main
        state: present
  when:
    - ansible_distribution | lower == 'debian'


- name: merge daemon configuration between defaults and custom
  set_fact:
    monit_daemon: "{{ monit_defaults_daemon |
      combine( monit_daemon, recursive=True ) }}"

- name: merge eventqueue configuration between defaults and custom
  set_fact:
    monit_eventqueue: "{{ monit_defaults_eventqueue |
      combine( monit_eventqueue, recursive=True ) }}"

- name: merge mail configuration between defaults and custom
  set_fact:
    monit_mail: "{{ monit_defaults_mail |
      combine( monit_mail, recursive=True ) }}"

- name: merge webinterface configuration between defaults and custom
  set_fact:
    monit_webinterface: "{{ monit_defaults_webinterface |
      combine( monit_webinterface, recursive=True ) }}"

- name: make sure ansible local facts directory exists
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: update package cache
  package:
    update_cache: true

...
