---

- name: restart monit
  ansible.builtin.service:
    name: "{{ monit_service }}"
    state: restarted

- name: reload monit
  ansible.builtin.service:
    name: "{{ monit_service }}"
    state: reloaded

- name: validate config
  ansible.builtin.command: |
    monit -t

...
